import type { NextPage } from 'next'
import Head from 'next/head'
import useSWR from 'swr'
import CustomCalendar from '../components/CustomCalendar'

const fetcher = () => fetch('/api/events').then(res => res.json())

const Home: NextPage = () => {
  const { data: events, error } = useSWR(`/api/events`, fetcher)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CustomCalendar events={events}/>
    </div>
  )
}

export default Home
