import dayjs from 'dayjs'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import useSWR from 'swr'
import ReactCustomCalendar from '../components/calendar/CustomCalendar'

const fetcher = ({ year, month }: { year: number, month: number }) => {
  const params = {
    year: `${year}`,
    month: `${month}`
  }
  const query = new URLSearchParams(params)
  return fetch(`/api/events?${query}`).then(res => res.json())
}

const Home: NextPage = () => {
  const [baseDate, setBaseDate] = useState(dayjs())
  const { data: events = [], error } = useSWR(`/api/events?year=${baseDate.year()}&month=${baseDate.month()}`, () => fetcher({ year: baseDate.year(), month: baseDate.month() }))
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ReactCustomCalendar
        baseDate={baseDate}
        events={events}
      />
    </div>
  )
}

export default Home
